export const NFTs = [
    {
      Id: 1,
      Badge: "82,571",
      ImageUrl: "/images/nft/bking.png",
      Edition: 371,
      Stock: 128,
      Title: "KING BITCOIN",
      Price: "$10M",
  
      Avatar: "/images/avatar/newk3d.png",
      Author: "newk3d",
      Likes: 652,
    },
    {
      Id: 2,
      Badge: "82,571",
      ImageUrl: "/images/nft/bking.png",
      Edition: 371,
      Stock: 128,
      Title: "KING BITCOIN",
      Price: "$10M",
      Avatar: "/images/avatar/newk3d.png",
      Author: "newk3d",
      Likes: 652,
    },
    {
      Id: 3,
      Badge: "82,571",
      ImageUrl: "/images/nft/bking.png",
      Edition: 371,
      Stock: 128,
      Title: "KING BITCOIN",
      Price: "$10M",
      Avatar: "/images/avatar/newk3d.png",
      Author: "newk3d",
      Likes: 652,
    },
    {
      Id: 4,
      Badge: "82,571",
      ImageUrl: "/images/nft/bking.png",
      Edition: 371,
      Stock: 128,
      Title: "KING BITCOIN",
      Price: "$10M",
      Avatar: "/images/avatar/newk3d.png",
      Author: "newk3d",
      Likes: 652,
    },
    {
      Id: 5,
      Badge: "82,571",
      ImageUrl: "/images/nft/bking.png",
      Edition: 371,
      Stock: 128,
      Title: "KING BITCOIN",
      Price: "$10M",
      Avatar: "/images/avatar/newk3d.png",
      Author: "newk3d",
      Likes: 652,
    },
    {
      Id: 6,
      Badge: "82,571",
      ImageUrl: "/images/nft/bking.png",
      Edition: 371,
      Stock: 128,
      Title: "KING BITCOIN",
      Price: "$10M",
      Avatar: "/images/avatar/newk3d.png",
      Author: "newk3d",
      Likes: 652,
    },
  ];